# Site
repository: edraizen/edraizen.github.io
# favicon: images/favicon.ico

# Personal info
name: Eli Draizen
title: PhD Candidate in Phil Bourne's lab @ University of Virginia
email: edraizen@gmail.com
website: edraizen.github.io

# Social links
twitter_username: EliDraizen
github_username:  edraizen
linkedin_username: EliDraizen
googleplus_username: https://scholar.google.com/citations?user=As4Mi1cAAAAJ

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I am a PhD Candidate at the University of Virginia in the labs of <a href="http://bournelab.org/">Phil Bourne and Cameron Mura</a>.
  I am interested in structural bioinformatics and machine learning applied to protein evolution and host-pathogen interactions.
  I was previosly an organizer for the <a href="https://iscb-dc-rsg.github.io/">ISCB Region Student Group in DC</a> as the Student Council Symposiums at the main ISCB conference.

  You can download my full CV <a href="DraizenCV2020.pdf">here<a>.

# Projects Section
# projects_title: Projects

# Experience Section
experience_title: Publications

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
# more_content: | # this will include new lines to allow paragraphs
#   Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#    - Climbing
#    - Gaming
#    - Knitting
#    - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: edraizen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
